[project]
name = "yc-s3-poller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.28",
    "kafka-python-ng>=2.2.3",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
]
